language: julia

julia:
  - 1.1

os:
  - linux

notifications:
  email: false
before_install:
  - pip install libsbml 
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project -e 'using Pkg; Pkg.build(; verbose = true); Pkg.test(coverage=true)'
      after_success: skip
