language: julia

julia:
  - 1.1

python: 
  - 3.6 

os:
  - linux

notifications:
  email: false
before_install:
  - sudo apt-get -y install python3-pip 
  - pip3 install python-libsbml 
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --color=yes --project -e 'using Pkg; Pkg.build(; verbose = true); Pkg.test(coverage=true)'
      after_success: skip
