language: julia

julia:
  - 1.1
  - 1.2
  - 1.3

os:
  - linux

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --color=yes --project -e 'using Pkg; Pkg.build(; verbose = true); Pkg.test(coverage=true)'
      after_success: skip
